package ch.app.hk.bank.locator.core.design.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFF006C4D)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFF88F8C8)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF002115)
val md_theme_light_secondary = Color(color = 0xFF4D6358)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFFCFE9D9)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF092016)
val md_theme_light_tertiary = Color(color = 0xFF3E6374)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFFC1E8FC)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF001F29)
val md_theme_light_error = Color(color = 0xFFBA1A1A)
val md_theme_light_errorContainer = Color(color = 0xFFFFDAD6)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(color = 0xFF410002)
val md_theme_light_background = Color(color = 0xFFFBFDF9)
val md_theme_light_onBackground = Color(color = 0xFF191C1A)
val md_theme_light_surface = Color(color = 0xFFFBFDF9)
val md_theme_light_onSurface = Color(color = 0xFF191C1A)
val md_theme_light_surfaceVariant = Color(color = 0xFFDBE5DD)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF404944)
val md_theme_light_outline = Color(color = 0xFF707973)
val md_theme_light_inverseOnSurface = Color(color = 0xFFEFF1ED)
val md_theme_light_inverseSurface = Color(color = 0xFF2E312F)
val md_theme_light_inversePrimary = Color(color = 0xFF6BDBAD)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFF006C4D)
val md_theme_light_outlineVariant = Color(color = 0xFFBFC9C2)
val md_theme_light_scrim = Color(color = 0xFF000000)

val md_theme_dark_primary = Color(color = 0xFF6BDBAD)
val md_theme_dark_onPrimary = Color(color = 0xFF003826)
val md_theme_dark_primaryContainer = Color(color = 0xFF005139)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFF88F8C8)
val md_theme_dark_secondary = Color(color = 0xFFB3CCBE)
val md_theme_dark_onSecondary = Color(color = 0xFF1F352B)
val md_theme_dark_secondaryContainer = Color(color = 0xFF354B40)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFFCFE9D9)
val md_theme_dark_tertiary = Color(color = 0xFFA5CCDF)
val md_theme_dark_onTertiary = Color(color = 0xFF083544)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF254B5B)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFFC1E8FC)
val md_theme_dark_error = Color(color = 0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(color = 0xFF93000A)
val md_theme_dark_onError = Color(color = 0xFF690005)
val md_theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_background = Color(color = 0xFF191C1A)
val md_theme_dark_onBackground = Color(color = 0xFFE1E3DF)
val md_theme_dark_surface = Color(color = 0xFF191C1A)
val md_theme_dark_onSurface = Color(color = 0xFFE1E3DF)
val md_theme_dark_surfaceVariant = Color(color = 0xFF404944)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFBFC9C2)
val md_theme_dark_outline = Color(color = 0xFF8A938D)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF191C1A)
val md_theme_dark_inverseSurface = Color(color = 0xFFE1E3DF)
val md_theme_dark_inversePrimary = Color(color = 0xFF006C4D)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFF6BDBAD)
val md_theme_dark_outlineVariant = Color(color = 0xFF404944)
val md_theme_dark_scrim = Color(color = 0xFF000000)

val seed = Color(color = 0xFF198964)
