name: android ci lint

on:
  workflow_call:

jobs:
  android-lint:
    name: android lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICE_JSON_DEBUG }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
      - name: lint
        run: |
          ./gradlew lintDebug
          cat app/build/reports/lint-results-debug.txt

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: ktlint check
        run: |
          ./gradlew ktlintCheck

  detekt:
    name: detekt
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: detekt check
        run: |
          ./gradlew detekt

  konsist:
    name: konsist
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: konsist check
        run: |
          ./gradlew :framework:konsist:test
