name: Android CI Lint

on:
  workflow_call:

jobs:
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: android-actions/setup-android@v3
      - name: ktlint check
        run: |
          ./gradlew ktlintCheck
  detekt:
    name: detekt
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: android-actions/setup-android@v3
      - name: detekt check
        run: |
          ./gradlew detekt
